symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # For full configuration see https://github.com/SymfonyCasts/reset-password-bundle#configuration
    # Temps minimal en secondes avant qu'un lien de réinitialisation puisse être à nouveau généré
    throttle_limit: 30
    # Durée maximale de validité d'un lien de réinitialisation de mot de passe
    lifetime: 3600

