security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  #password_hashers:
  password_hashers:
    # Use your user class name here
    App\Entity\User:
      algorithm: plaintextdg

    #Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  #    enable_authenticator_manager: true
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
    # used to reload user from session & other features (e.g. switch_user)
    # used to reload user from session & other features (e.g. switch_user)
    # used to reload user from session & other features (e.g. switch_user)
  firewalls:
    main:
      #            lazy: true
      #            anonymous: lazy
      #            guard:
      #                authenticators:
      #                    - App\Security\Authenticator
      logout:
        path: app_logout
        target: login
      form_login:
        # "app_login" is the name of the route created previously
        login_path: app_login
        check_path: app_login
      custom_authenticators:
        - App\Security\EasyamapAuthenticator
      entry_point: form_login

  access_control:
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }